export const core = {
    constants: {
        auth0: {
            GET_ACCESS_TOKEN_STARTED: 'GET_ACCESS_TOKEN_STARTED',
            GET_ACCESS_TOKEN_COMPLETE: 'GET_ACCESS_TOKEN_COMPLETE',
            GET_ACCESS_TOKEN_FAILED: 'GET_ACCESS_TOKEN_FAILED',
            IS_TOKEN_VALIDATED:'IS_TOKEN_VALIDATED',
            VALIDATE_TOKEN_COMPLETE: 'VALIDATE_TOKEN_COMPLETE',
            LOGOUT: 'LOGOUT',
            ERROR: 'ERROR'
        }
    }
}